#trying to see if it could work if the iso image is using fedora but installs my image lmao
name: Build Custom ISO

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:
      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v9

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@main
        with:
          image-ref: quay.io/fedora/fedora-bootc:latest
#          flatpaks-list: ${{ github.workspace }}/config/flatpaks.list #already done by bluebuild
#          hook-post-rootfs: ${{ github.workspace }}/config/configure-iso.sh
          compression: squashfs
          builder-distro: fedora
          livesys: false
          container-image: ghcr.io/fluoritebyte/upurple:latest

      - name: Rename ISO
        run: |
          mkdir -p output
          mv ${{ steps.build.outputs.iso-dest }} output/custom-image-$(date +%Y%m%d).iso
          (cd output && sha256sum *.iso | tee CHECKSUMS)

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: custom-iso
          path: output/
